language: objective-c
before_install: cd Example && pod install && cd -
script:
- xctool test -workspace Example/AMPActivityIndicator.xcworkspace -scheme AMPActivityIndicator -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
