language: objective-c
before_install: cd Example && pod install && pod update AMPActivityIndicator && cd -
script:
- xctool -workspace Example/AMPActivityIndicator.xcworkspace -scheme AMPActivityIndicator -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
